### ISSUE TITLE
Unable to close app importing BullModule

### ISSUE THREAD

**Issue by mortimr** [nestjs/bull#197]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
Right now, an app importing the BullModule is not able to shutdown properly. This is a big issue for e2e testing. Tried building the module both in sync and async mode and got the issue on both tries.

## Expected behavior
Module should clear its open handles when app closing / module being destroyed.

**Comment by kamilmysliwiec** [comment]
Fixed in the latest version.

**Comment by mortimr** [comment]
Great.

Amazing work btw @kamilmysliwiec

**Comment by codetheweb** [comment]
I think this may have regressed; I'm having this issue and so did at least one other person [5 months ago](https://stackoverflow.com/questions/62975121/close-redis-connection-when-using-nestjs-queues).

**Comment by StiliyanKushev** [comment]
Error is still happening, @kamilmysliwiec. Sorry for the ping, but can we fix this?
